// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: gorbage.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalPath  string                 `protobuf:"bytes,1,opt,name=original_path,json=originalPath,proto3" json:"original_path,omitempty"`
	Size          uint64                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	IsDirectory   bool                   `protobuf:"varint,3,opt,name=is_directory,json=isDirectory,proto3" json:"is_directory,omitempty"`
	Sha256        string                 `protobuf:"bytes,4,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileMetadata) Reset() {
	*x = FileMetadata{}
	mi := &file_gorbage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMetadata) ProtoMessage() {}

func (x *FileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_gorbage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMetadata.ProtoReflect.Descriptor instead.
func (*FileMetadata) Descriptor() ([]byte, []int) {
	return file_gorbage_proto_rawDescGZIP(), []int{0}
}

func (x *FileMetadata) GetOriginalPath() string {
	if x != nil {
		return x.OriginalPath
	}
	return ""
}

func (x *FileMetadata) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileMetadata) GetIsDirectory() bool {
	if x != nil {
		return x.IsDirectory
	}
	return false
}

func (x *FileMetadata) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type InitiateUploadRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Meta               *FileMetadata          `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	PreferredChunkSize uint64                 `protobuf:"varint,2,opt,name=preferred_chunk_size,json=preferredChunkSize,proto3" json:"preferred_chunk_size,omitempty"`
	Prefix             string                 `protobuf:"bytes,3,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *InitiateUploadRequest) Reset() {
	*x = InitiateUploadRequest{}
	mi := &file_gorbage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateUploadRequest) ProtoMessage() {}

func (x *InitiateUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gorbage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateUploadRequest.ProtoReflect.Descriptor instead.
func (*InitiateUploadRequest) Descriptor() ([]byte, []int) {
	return file_gorbage_proto_rawDescGZIP(), []int{1}
}

func (x *InitiateUploadRequest) GetMeta() *FileMetadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *InitiateUploadRequest) GetPreferredChunkSize() uint64 {
	if x != nil {
		return x.PreferredChunkSize
	}
	return 0
}

func (x *InitiateUploadRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type InitiateUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadId      string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	ChunkSize     uint64                 `protobuf:"varint,2,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	TotalChunks   uint64                 `protobuf:"varint,3,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	ExpiresAtUnix int64                  `protobuf:"varint,4,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateUploadResponse) Reset() {
	*x = InitiateUploadResponse{}
	mi := &file_gorbage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateUploadResponse) ProtoMessage() {}

func (x *InitiateUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gorbage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateUploadResponse.ProtoReflect.Descriptor instead.
func (*InitiateUploadResponse) Descriptor() ([]byte, []int) {
	return file_gorbage_proto_rawDescGZIP(), []int{2}
}

func (x *InitiateUploadResponse) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *InitiateUploadResponse) GetChunkSize() uint64 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *InitiateUploadResponse) GetTotalChunks() uint64 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *InitiateUploadResponse) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

type UploadPartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadId      string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	Seq           uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadPartRequest) Reset() {
	*x = UploadPartRequest{}
	mi := &file_gorbage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadPartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadPartRequest) ProtoMessage() {}

func (x *UploadPartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gorbage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadPartRequest.ProtoReflect.Descriptor instead.
func (*UploadPartRequest) Descriptor() ([]byte, []int) {
	return file_gorbage_proto_rawDescGZIP(), []int{3}
}

func (x *UploadPartRequest) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *UploadPartRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *UploadPartRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UploadPartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadPartResponse) Reset() {
	*x = UploadPartResponse{}
	mi := &file_gorbage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadPartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadPartResponse) ProtoMessage() {}

func (x *UploadPartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gorbage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadPartResponse.ProtoReflect.Descriptor instead.
func (*UploadPartResponse) Descriptor() ([]byte, []int) {
	return file_gorbage_proto_rawDescGZIP(), []int{4}
}

func (x *UploadPartResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type FileInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfoRequest) Reset() {
	*x = FileInfoRequest{}
	mi := &file_gorbage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfoRequest) ProtoMessage() {}

func (x *FileInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gorbage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfoRequest.ProtoReflect.Descriptor instead.
func (*FileInfoRequest) Descriptor() ([]byte, []int) {
	return file_gorbage_proto_rawDescGZIP(), []int{5}
}

func (x *FileInfoRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type DownloadRangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Offset        uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         uint64                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadRangeRequest) Reset() {
	*x = DownloadRangeRequest{}
	mi := &file_gorbage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRangeRequest) ProtoMessage() {}

func (x *DownloadRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gorbage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadRangeRequest.ProtoReflect.Descriptor instead.
func (*DownloadRangeRequest) Descriptor() ([]byte, []int) {
	return file_gorbage_proto_rawDescGZIP(), []int{6}
}

func (x *DownloadRangeRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *DownloadRangeRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *DownloadRangeRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type DownloadRangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        uint64                 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	TotalSize     uint64                 `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadRangeResponse) Reset() {
	*x = DownloadRangeResponse{}
	mi := &file_gorbage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadRangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRangeResponse) ProtoMessage() {}

func (x *DownloadRangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gorbage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadRangeResponse.ProtoReflect.Descriptor instead.
func (*DownloadRangeResponse) Descriptor() ([]byte, []int) {
	return file_gorbage_proto_rawDescGZIP(), []int{7}
}

func (x *DownloadRangeResponse) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *DownloadRangeResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DownloadRangeResponse) GetTotalSize() uint64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	OriginalPath  string                 `protobuf:"bytes,2,opt,name=original_path,json=originalPath,proto3" json:"original_path,omitempty"`
	Size          uint64                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	CreatedAtUnix int64                  `protobuf:"varint,4,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	IsDirectory   bool                   `protobuf:"varint,5,opt,name=is_directory,json=isDirectory,proto3" json:"is_directory,omitempty"`
	Sha256        string                 `protobuf:"bytes,6,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_gorbage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gorbage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_gorbage_proto_rawDescGZIP(), []int{8}
}

func (x *FileInfo) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *FileInfo) GetOriginalPath() string {
	if x != nil {
		return x.OriginalPath
	}
	return ""
}

func (x *FileInfo) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileInfo) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *FileInfo) GetIsDirectory() bool {
	if x != nil {
		return x.IsDirectory
	}
	return false
}

func (x *FileInfo) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_gorbage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gorbage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_gorbage_proto_rawDescGZIP(), []int{9}
}

func (x *ListRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*FileInfo            `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_gorbage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gorbage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_gorbage_proto_rawDescGZIP(), []int{10}
}

func (x *ListResponse) GetFiles() []*FileInfo {
	if x != nil {
		return x.Files
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_gorbage_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gorbage_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_gorbage_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_gorbage_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gorbage_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_gorbage_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_gorbage_proto protoreflect.FileDescriptor

const file_gorbage_proto_rawDesc = "" +
	"\n" +
	"\rgorbage.proto\x12\agorbage\"\x82\x01\n" +
	"\fFileMetadata\x12#\n" +
	"\roriginal_path\x18\x01 \x01(\tR\foriginalPath\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04size\x12!\n" +
	"\fis_directory\x18\x03 \x01(\bR\visDirectory\x12\x16\n" +
	"\x06sha256\x18\x04 \x01(\tR\x06sha256\"\x8c\x01\n" +
	"\x15InitiateUploadRequest\x12)\n" +
	"\x04meta\x18\x01 \x01(\v2\x15.gorbage.FileMetadataR\x04meta\x120\n" +
	"\x14preferred_chunk_size\x18\x02 \x01(\x04R\x12preferredChunkSize\x12\x16\n" +
	"\x06prefix\x18\x03 \x01(\tR\x06prefix\"\x9f\x01\n" +
	"\x16InitiateUploadResponse\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x02 \x01(\x04R\tchunkSize\x12!\n" +
	"\ftotal_chunks\x18\x03 \x01(\x04R\vtotalChunks\x12&\n" +
	"\x0fexpires_at_unix\x18\x04 \x01(\x03R\rexpiresAtUnix\"V\n" +
	"\x11UploadPartRequest\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"$\n" +
	"\x12UploadPartResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\")\n" +
	"\x0fFileInfoRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\"\\\n" +
	"\x14DownloadRangeRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x04R\x05limit\"b\n" +
	"\x15DownloadRangeResponse\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x04R\x06offset\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1d\n" +
	"\n" +
	"total_size\x18\x03 \x01(\x04R\ttotalSize\"\xbe\x01\n" +
	"\bFileInfo\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x12#\n" +
	"\roriginal_path\x18\x02 \x01(\tR\foriginalPath\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x04R\x04size\x12&\n" +
	"\x0fcreated_at_unix\x18\x04 \x01(\x03R\rcreatedAtUnix\x12!\n" +
	"\fis_directory\x18\x05 \x01(\bR\visDirectory\x12\x16\n" +
	"\x06sha256\x18\x06 \x01(\tR\x06sha256\"%\n" +
	"\vListRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\"7\n" +
	"\fListResponse\x12'\n" +
	"\x05files\x18\x01 \x03(\v2\x11.gorbage.FileInfoR\x05files\"'\n" +
	"\rDeleteRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xa6\x03\n" +
	"\x0eStorageService\x12Q\n" +
	"\x0eInitiateUpload\x12\x1e.gorbage.InitiateUploadRequest\x1a\x1f.gorbage.InitiateUploadResponse\x12E\n" +
	"\n" +
	"UploadPart\x12\x1a.gorbage.UploadPartRequest\x1a\x1b.gorbage.UploadPartResponse\x12N\n" +
	"\rDownloadRange\x12\x1d.gorbage.DownloadRangeRequest\x1a\x1e.gorbage.DownloadRangeResponse\x123\n" +
	"\x04List\x12\x14.gorbage.ListRequest\x1a\x15.gorbage.ListResponse\x12:\n" +
	"\vGetFileInfo\x12\x18.gorbage.FileInfoRequest\x1a\x11.gorbage.FileInfo\x129\n" +
	"\x06Delete\x12\x16.gorbage.DeleteRequest\x1a\x17.gorbage.DeleteResponseB0Z.github.com/gabkaclassic/gorbage/internal/protob\x06proto3"

var (
	file_gorbage_proto_rawDescOnce sync.Once
	file_gorbage_proto_rawDescData []byte
)

func file_gorbage_proto_rawDescGZIP() []byte {
	file_gorbage_proto_rawDescOnce.Do(func() {
		file_gorbage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gorbage_proto_rawDesc), len(file_gorbage_proto_rawDesc)))
	})
	return file_gorbage_proto_rawDescData
}

var file_gorbage_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_gorbage_proto_goTypes = []any{
	(*FileMetadata)(nil),           // 0: gorbage.FileMetadata
	(*InitiateUploadRequest)(nil),  // 1: gorbage.InitiateUploadRequest
	(*InitiateUploadResponse)(nil), // 2: gorbage.InitiateUploadResponse
	(*UploadPartRequest)(nil),      // 3: gorbage.UploadPartRequest
	(*UploadPartResponse)(nil),     // 4: gorbage.UploadPartResponse
	(*FileInfoRequest)(nil),        // 5: gorbage.FileInfoRequest
	(*DownloadRangeRequest)(nil),   // 6: gorbage.DownloadRangeRequest
	(*DownloadRangeResponse)(nil),  // 7: gorbage.DownloadRangeResponse
	(*FileInfo)(nil),               // 8: gorbage.FileInfo
	(*ListRequest)(nil),            // 9: gorbage.ListRequest
	(*ListResponse)(nil),           // 10: gorbage.ListResponse
	(*DeleteRequest)(nil),          // 11: gorbage.DeleteRequest
	(*DeleteResponse)(nil),         // 12: gorbage.DeleteResponse
}
var file_gorbage_proto_depIdxs = []int32{
	0,  // 0: gorbage.InitiateUploadRequest.meta:type_name -> gorbage.FileMetadata
	8,  // 1: gorbage.ListResponse.files:type_name -> gorbage.FileInfo
	1,  // 2: gorbage.StorageService.InitiateUpload:input_type -> gorbage.InitiateUploadRequest
	3,  // 3: gorbage.StorageService.UploadPart:input_type -> gorbage.UploadPartRequest
	6,  // 4: gorbage.StorageService.DownloadRange:input_type -> gorbage.DownloadRangeRequest
	9,  // 5: gorbage.StorageService.List:input_type -> gorbage.ListRequest
	5,  // 6: gorbage.StorageService.GetFileInfo:input_type -> gorbage.FileInfoRequest
	11, // 7: gorbage.StorageService.Delete:input_type -> gorbage.DeleteRequest
	2,  // 8: gorbage.StorageService.InitiateUpload:output_type -> gorbage.InitiateUploadResponse
	4,  // 9: gorbage.StorageService.UploadPart:output_type -> gorbage.UploadPartResponse
	7,  // 10: gorbage.StorageService.DownloadRange:output_type -> gorbage.DownloadRangeResponse
	10, // 11: gorbage.StorageService.List:output_type -> gorbage.ListResponse
	8,  // 12: gorbage.StorageService.GetFileInfo:output_type -> gorbage.FileInfo
	12, // 13: gorbage.StorageService.Delete:output_type -> gorbage.DeleteResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_gorbage_proto_init() }
func file_gorbage_proto_init() {
	if File_gorbage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gorbage_proto_rawDesc), len(file_gorbage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gorbage_proto_goTypes,
		DependencyIndexes: file_gorbage_proto_depIdxs,
		MessageInfos:      file_gorbage_proto_msgTypes,
	}.Build()
	File_gorbage_proto = out.File
	file_gorbage_proto_goTypes = nil
	file_gorbage_proto_depIdxs = nil
}
