// Code generated by mockery v2.53.6. DO NOT EDIT.

package proto

import mock "github.com/stretchr/testify/mock"

// MockUnsafeStorageServiceServer is an autogenerated mock type for the UnsafeStorageServiceServer type
type MockUnsafeStorageServiceServer struct {
	mock.Mock
}

type MockUnsafeStorageServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUnsafeStorageServiceServer) EXPECT() *MockUnsafeStorageServiceServer_Expecter {
	return &MockUnsafeStorageServiceServer_Expecter{mock: &_m.Mock}
}

// mustEmbedUnimplementedStorageServiceServer provides a mock function with no fields
func (_m *MockUnsafeStorageServiceServer) mustEmbedUnimplementedStorageServiceServer() {
	_m.Called()
}

// MockUnsafeStorageServiceServer_mustEmbedUnimplementedStorageServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedStorageServiceServer'
type MockUnsafeStorageServiceServer_mustEmbedUnimplementedStorageServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedStorageServiceServer is a helper method to define mock.On call
func (_e *MockUnsafeStorageServiceServer_Expecter) mustEmbedUnimplementedStorageServiceServer() *MockUnsafeStorageServiceServer_mustEmbedUnimplementedStorageServiceServer_Call {
	return &MockUnsafeStorageServiceServer_mustEmbedUnimplementedStorageServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedStorageServiceServer")}
}

func (_c *MockUnsafeStorageServiceServer_mustEmbedUnimplementedStorageServiceServer_Call) Run(run func()) *MockUnsafeStorageServiceServer_mustEmbedUnimplementedStorageServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUnsafeStorageServiceServer_mustEmbedUnimplementedStorageServiceServer_Call) Return() *MockUnsafeStorageServiceServer_mustEmbedUnimplementedStorageServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUnsafeStorageServiceServer_mustEmbedUnimplementedStorageServiceServer_Call) RunAndReturn(run func()) *MockUnsafeStorageServiceServer_mustEmbedUnimplementedStorageServiceServer_Call {
	_c.Run(run)
	return _c
}

// NewMockUnsafeStorageServiceServer creates a new instance of MockUnsafeStorageServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnsafeStorageServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnsafeStorageServiceServer {
	mock := &MockUnsafeStorageServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
