// Code generated by mockery v2.53.6. DO NOT EDIT.

package client

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockStorageClient is an autogenerated mock type for the StorageClient type
type MockStorageClient struct {
	mock.Mock
}

type MockStorageClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorageClient) EXPECT() *MockStorageClient_Expecter {
	return &MockStorageClient_Expecter{mock: &_m.Mock}
}

// DeleteArtifact provides a mock function with given fields: ctx, prefix
func (_m *MockStorageClient) DeleteArtifact(ctx context.Context, prefix string) error {
	ret := _m.Called(ctx, prefix)

	if len(ret) == 0 {
		panic("no return value specified for DeleteArtifact")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, prefix)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorageClient_DeleteArtifact_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteArtifact'
type MockStorageClient_DeleteArtifact_Call struct {
	*mock.Call
}

// DeleteArtifact is a helper method to define mock.On call
//   - ctx context.Context
//   - prefix string
func (_e *MockStorageClient_Expecter) DeleteArtifact(ctx interface{}, prefix interface{}) *MockStorageClient_DeleteArtifact_Call {
	return &MockStorageClient_DeleteArtifact_Call{Call: _e.mock.On("DeleteArtifact", ctx, prefix)}
}

func (_c *MockStorageClient_DeleteArtifact_Call) Run(run func(ctx context.Context, prefix string)) *MockStorageClient_DeleteArtifact_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStorageClient_DeleteArtifact_Call) Return(_a0 error) *MockStorageClient_DeleteArtifact_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorageClient_DeleteArtifact_Call) RunAndReturn(run func(context.Context, string) error) *MockStorageClient_DeleteArtifact_Call {
	_c.Call.Return(run)
	return _c
}

// DownloadArtifact provides a mock function with given fields: ctx, prefix, filepath, keyPath, workers, chunkSize
func (_m *MockStorageClient) DownloadArtifact(ctx context.Context, prefix string, filepath string, keyPath string, workers int64, chunkSize int64) error {
	ret := _m.Called(ctx, prefix, filepath, keyPath, workers, chunkSize)

	if len(ret) == 0 {
		panic("no return value specified for DownloadArtifact")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int64, int64) error); ok {
		r0 = rf(ctx, prefix, filepath, keyPath, workers, chunkSize)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorageClient_DownloadArtifact_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadArtifact'
type MockStorageClient_DownloadArtifact_Call struct {
	*mock.Call
}

// DownloadArtifact is a helper method to define mock.On call
//   - ctx context.Context
//   - prefix string
//   - filepath string
//   - keyPath string
//   - workers int64
//   - chunkSize int64
func (_e *MockStorageClient_Expecter) DownloadArtifact(ctx interface{}, prefix interface{}, filepath interface{}, keyPath interface{}, workers interface{}, chunkSize interface{}) *MockStorageClient_DownloadArtifact_Call {
	return &MockStorageClient_DownloadArtifact_Call{Call: _e.mock.On("DownloadArtifact", ctx, prefix, filepath, keyPath, workers, chunkSize)}
}

func (_c *MockStorageClient_DownloadArtifact_Call) Run(run func(ctx context.Context, prefix string, filepath string, keyPath string, workers int64, chunkSize int64)) *MockStorageClient_DownloadArtifact_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(int64), args[5].(int64))
	})
	return _c
}

func (_c *MockStorageClient_DownloadArtifact_Call) Return(_a0 error) *MockStorageClient_DownloadArtifact_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorageClient_DownloadArtifact_Call) RunAndReturn(run func(context.Context, string, string, string, int64, int64) error) *MockStorageClient_DownloadArtifact_Call {
	_c.Call.Return(run)
	return _c
}

// GetFileInfo provides a mock function with given fields: ctx, prefix
func (_m *MockStorageClient) GetFileInfo(ctx context.Context, prefix string) error {
	ret := _m.Called(ctx, prefix)

	if len(ret) == 0 {
		panic("no return value specified for GetFileInfo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, prefix)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorageClient_GetFileInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFileInfo'
type MockStorageClient_GetFileInfo_Call struct {
	*mock.Call
}

// GetFileInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - prefix string
func (_e *MockStorageClient_Expecter) GetFileInfo(ctx interface{}, prefix interface{}) *MockStorageClient_GetFileInfo_Call {
	return &MockStorageClient_GetFileInfo_Call{Call: _e.mock.On("GetFileInfo", ctx, prefix)}
}

func (_c *MockStorageClient_GetFileInfo_Call) Run(run func(ctx context.Context, prefix string)) *MockStorageClient_GetFileInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStorageClient_GetFileInfo_Call) Return(_a0 error) *MockStorageClient_GetFileInfo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorageClient_GetFileInfo_Call) RunAndReturn(run func(context.Context, string) error) *MockStorageClient_GetFileInfo_Call {
	_c.Call.Return(run)
	return _c
}

// LoadArtifactsList provides a mock function with given fields: ctx, prefix
func (_m *MockStorageClient) LoadArtifactsList(ctx context.Context, prefix string) error {
	ret := _m.Called(ctx, prefix)

	if len(ret) == 0 {
		panic("no return value specified for LoadArtifactsList")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, prefix)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorageClient_LoadArtifactsList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadArtifactsList'
type MockStorageClient_LoadArtifactsList_Call struct {
	*mock.Call
}

// LoadArtifactsList is a helper method to define mock.On call
//   - ctx context.Context
//   - prefix string
func (_e *MockStorageClient_Expecter) LoadArtifactsList(ctx interface{}, prefix interface{}) *MockStorageClient_LoadArtifactsList_Call {
	return &MockStorageClient_LoadArtifactsList_Call{Call: _e.mock.On("LoadArtifactsList", ctx, prefix)}
}

func (_c *MockStorageClient_LoadArtifactsList_Call) Run(run func(ctx context.Context, prefix string)) *MockStorageClient_LoadArtifactsList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStorageClient_LoadArtifactsList_Call) Return(_a0 error) *MockStorageClient_LoadArtifactsList_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorageClient_LoadArtifactsList_Call) RunAndReturn(run func(context.Context, string) error) *MockStorageClient_LoadArtifactsList_Call {
	_c.Call.Return(run)
	return _c
}

// UploadArtifact provides a mock function with given fields: ctx, prefix, filepath, keyPath, workers, chunkSize
func (_m *MockStorageClient) UploadArtifact(ctx context.Context, prefix string, filepath string, keyPath string, workers int64, chunkSize int64) error {
	ret := _m.Called(ctx, prefix, filepath, keyPath, workers, chunkSize)

	if len(ret) == 0 {
		panic("no return value specified for UploadArtifact")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int64, int64) error); ok {
		r0 = rf(ctx, prefix, filepath, keyPath, workers, chunkSize)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorageClient_UploadArtifact_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadArtifact'
type MockStorageClient_UploadArtifact_Call struct {
	*mock.Call
}

// UploadArtifact is a helper method to define mock.On call
//   - ctx context.Context
//   - prefix string
//   - filepath string
//   - keyPath string
//   - workers int64
//   - chunkSize int64
func (_e *MockStorageClient_Expecter) UploadArtifact(ctx interface{}, prefix interface{}, filepath interface{}, keyPath interface{}, workers interface{}, chunkSize interface{}) *MockStorageClient_UploadArtifact_Call {
	return &MockStorageClient_UploadArtifact_Call{Call: _e.mock.On("UploadArtifact", ctx, prefix, filepath, keyPath, workers, chunkSize)}
}

func (_c *MockStorageClient_UploadArtifact_Call) Run(run func(ctx context.Context, prefix string, filepath string, keyPath string, workers int64, chunkSize int64)) *MockStorageClient_UploadArtifact_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(int64), args[5].(int64))
	})
	return _c
}

func (_c *MockStorageClient_UploadArtifact_Call) Return(_a0 error) *MockStorageClient_UploadArtifact_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorageClient_UploadArtifact_Call) RunAndReturn(run func(context.Context, string, string, string, int64, int64) error) *MockStorageClient_UploadArtifact_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorageClient creates a new instance of MockStorageClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorageClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorageClient {
	mock := &MockStorageClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
